### ISSUE TITLE
Crash related to Audio

### ISSUE THREAD

**Issue by whatisor** [haiyangwu/mediasoup-client-android#12] opened 2020-03-21 07:28 UTC
When "WebSockets connection lost", application crash with below ERROR log:

`No implementation found for void org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(int, long) (tried Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData and Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData__IJ)
03-21 14:26:08.102 3914-4000/ /AndroidRuntime: FATAL EXCEPTION: AudioTrackJavaThread
    Process: com.immertec.vr, PID: 3914
    java.lang.Error: FATAL EXCEPTION [AudioTrackJavaThread]
    Unity version     : 2018.4.18f1
    Device model      : unknown Android SDK built for x86
    Device fingerprint: Android/sdk_google_phone_x86/generic_x86:6.0/MASTER/5525988:userdebug/test-keys
    
    Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(int, long) (tried Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData and Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData__IJ)
        at org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(Native Method)
        at org.webrtc.voiceengine.WebRtcAudioTrack.access$400(WebRtcAudioTrack.java:28)
        at org.webrtc.voiceengine.WebRtcAudioTrack$AudioTrackThread.run(WebRtcAudioTrack.java:147)`

**Comment by ethand91** [comment] 2020-04-10 10:15
Does the crash happen randomly?
Or is there a way to reproduce this issue?

**Comment by whatisor** [comment] 2020-04-10 13:59
@ethand91 ,as described, "WebSockets connection lost".
My network quality is bad, sometimes it disconnected to https://v3demo.mediasoup.org/, then it occurs

**Comment by gongwj1119** [comment] 2020-04-16 00:44
@ethand91 Has the crash been solved？

**Comment by gongwj1119** [comment] 2020-04-16 00:57
@whatisor @ethand91 Has the crash been solved？

**Comment by haiyangwu** [comment] 2020-04-22 06:22
@gongwj1119 @whatisor Would you try the latest version, I've modified the implementation of `xx-jni.cpp` and the crash never happened during my local test.

**Comment by PhilanthropistBright** [comment] 2020-04-29 09:18
I had the same problem, and in the Demo it crashed just by switching the network

**Comment by lusfold** [comment] 2020-05-18 06:50
java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(int, long) (tried Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData and Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData__IJ) at org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(Native Method)

**Comment by foobra** [comment] 2020-05-20 08:51
> @gongwj1119 @whatisor Would you try the latest version, I've modified the implementation of `xx-jni.cpp` and the crash never happened during my local test.

do you push your local change to github? I didn't see any change about xx-jni.cpp during last 30days

**Comment by linklinklinklin** [comment] 2020-06-10 06:13
@haiyangwu @gongwj1119 @whatisor still crash when I close RecvTransport, has the crash been solved？      
 # AudioTrackJavaThread(985)
java.lang.UnsatisfiedLinkError
No implementation found for void org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(int, long) (tried Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData and Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData__IJ)

**Comment by linklinklinklin** [comment] 2020-06-10 06:24
@haiyangwu 大佬好，当我运行代码 recvTransport.close()时候会出现下面这个异常。请问是什么原因呢， 是创建transport的时候要注意哪些问题还是什么原因呀? 望回复，谢谢！
java.lang.UnsatisfiedLinkError
No implementation found for void org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(int, long) (tried Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData and Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData__IJ)

**Comment by wujianwei121** [comment] 2020-06-19 07:46
@linsunshinecoder RoomClient->JoinImpl    if (mMediasoupDevice == null) {
                mMediasoupDevice = new Device();
                String routerRtpCapabilities = mProtoo.syncRequest("getRouterRtpCapabilities");
                mMediasoupDevice.load(routerRtpCapabilities);
            }
Mmediasaupdevice was created repeatedly

**Comment by pintukumarpatil** [comment] 2020-07-08 10:19
org.mediasoup.droid.demo E/soup.droid.dem: No implementation found for void org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(int, long) (tried Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData and Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData__IJ)
FATAL EXCEPTION: AudioTrackJavaThread
Process: org.mediasoup.droid.demo, PID: 11162
java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(int, long) (tried Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData and Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData__IJ)
at org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(Native Method)
at org.webrtc.voiceengine.WebRtcAudioTrack.access$400(WebRtcAudioTrack.java:28)
at org.webrtc.voiceengine.WebRtcAudioTrack$AudioTrackThread.run(WebRtcAudioTrack.java:147)

facing same issue

**Comment by Ben0421** [comment] 2020-07-13 14:31
I can reproduce this error by:
1 - Creating both send and receive transports
2 - Connecting sendTransport by producing
3 - Pausing the producer
4 - Connecting recvTransport by consuming
5 - Stopping the consumer
6 - Closing the recvTransport
7 - Disposing the recvTransport <-- After disposing, app will crash soon
8 - Recreating the recvTransport in the server and than the client

App crashes after disposing of the recvTransport if the sendTransport is connected (a producer is created on this transport and has produced). The crash can be reproduced quite easily following those steps on two devices (other devices tested work as intended).

The devices where this crash happens are armeabi-v7a Android 6.0.1 device (2 different manufacturers) and a Android 5.1-v7a device. This isn't specific to armv7a as devices with v7a/Android 7.1 work as expected.

PeerConnectionFactory is created a single time and MediasoupDevice is also only created once. I am using a build with the latest commits (26 june).

Any help is appreciated!

E/ACRA: ACRA caught a UnsatisfiedLinkError for com.ex.app
    java.lang.UnsatisfiedLinkError: No implementation found for void org.webrtc.voiceengine.WebRtcAudioRecord.nativeDataIsRecorded(int, long) (tried Java_org_webrtc_voiceengine_WebRtcAudioRecord_nativeDataIsRecorded and Java_org_webrtc_voiceengine_WebRtcAudioRecord_nativeDataIsRecorded__IJ)
        at org.webrtc.voiceengine.WebRtcAudioRecord.nativeDataIsRecorded(Native Method)
        at org.webrtc.voiceengine.WebRtcAudioRecord.access$600(WebRtcAudioRecord.java:26)
        at org.webrtc.voiceengine.WebRtcAudioRecord$AudioRecordThread.run(WebRtcAudioRecord.java:166)

**Comment by Ben0421** [comment] 2020-07-14 14:21
> 
> 
> @haiyangwu 大佬好，当我运行代码 recvTransport.close()时候会出现下面这个异常。请问是什么原因呢， 是创建transport的时候要注意哪些问题还是什么原因呀? 望回复，谢谢！
> 
> > java.lang.UnsatisfiedLinkError
> > No implementation found for void org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(int, long) (tried Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData and Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData__IJ)

Did you call recvTransport.close() before or after sendTransport.close() ? Did you call .dispose() for both transports? What Android version is affected?

**Comment by wujianwei121** [comment] 2020-07-15 01:17
我其实也没有完全解决&nbsp; 我偶尔关闭也会出现这个bug&nbsp; 但是几率很小&nbsp; 我改过源码关闭顺序&nbsp; 把这两个放在前面执行了&nbsp; &nbsp; 你试试看看&nbsp; &nbsp; 这个我以前也没有用过&nbsp;&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ben0421"<notifications@github.com&gt;; 
发送时间: 2020年7月14日(星期二) 晚上10:22
收件人: "haiyangwu/mediasoup-client-android"<mediasoup-client-android@noreply.github.com&gt;; 
抄送: "℉ōrēvēr."<417757407@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [haiyangwu/mediasoup-client-android] Crash related to Audio (#12)





  
@haiyangwu 大佬好，当我运行代码 recvTransport.close()时候会出现下面这个异常。请问是什么原因呢， 是创建transport的时候要注意哪些问题还是什么原因呀? 望回复，谢谢！
  
java.lang.UnsatisfiedLinkError
 No implementation found for void org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutData(int, long) (tried Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData and Java_org_webrtc_voiceengine_WebRtcAudioTrack_nativeGetPlayoutData__IJ)
   
Did you call recvTransport.close() before or after sendTransport.close() ? Did you call .dispose() for both transports? What Android version is affected?

**Comment by haitunSasa** [comment] 2020-07-23 06:08
I think I have fixed this problem. 
In the webrtc  issues, there also have this problem. https://bugs.chromium.org/p/webrtc/issues/detail?id=7587
The reason is that only one audio device module supported on Android. 
In this code, when join the room, the peerConnectionFactory has been created 4 times and each time will create one audio device module.So I try to create only one peerConnectionFactory in java, and  add peerconnection options params in device.cpp. 
Finally, it works.  
I hope it helps you.

**Comment by wujianwei121** [comment] 2020-07-24 08:18
Thanks 兄嘚




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "haiyangwu/mediasoup-client-android"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月23日(星期四) 下午2:08
收件人:&nbsp;"haiyangwu/mediasoup-client-android"<mediasoup-client-android@noreply.github.com&gt;;
抄送:&nbsp;"℉ōrēvēr."<417757407@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [haiyangwu/mediasoup-client-android] Crash related to Audio (#12)





 
I think I have fixed this problem.
 In the webrtc  issues, there also have this problem. https://bugs.chromium.org/p/webrtc/issues/detail?id=7587
 The reason is that only one audio device module supported on Android.
 In this code, when join the room, the peerConnectionFactory has been created 4 times and each time will create one audio device module.So I try to create only one peerConnectionFactory in java, and  add peerconnection options params in device.cpp.
 Finally, it works.
 I hope it helps you.

**Comment by Ben0421** [comment] 2020-08-13 12:18
> 
> 
> I think I have fixed this problem.
> In the webrtc issues, there also have this problem. https://bugs.chromium.org/p/webrtc/issues/detail?id=7587
> The reason is that only one audio device module supported on Android.
> In this code, when join the room, the peerConnectionFactory has been created 4 times and each time will create one audio device module.So I try to create only one peerConnectionFactory in java, and add peerconnection options params in device.cpp.
> Finally, it works.
> I hope it helps you.

Nice catch! libmediasoup creates multiple peer connection factories by default, including when creating a Device. Did you do a commit of the patch you applied? I checked your fork of this project but unfortunately it did not include any changes. Would you be open to sharing the solution?

**Comment by skgwazap** [comment] 2020-08-27 12:53
I've scribbled something here https://github.com/haiyangwu/mediasoup-client-android/pull/42

**Comment by janus-xiao** [comment] 2020-10-17 07:48
libmediasoupclient_ so.so How to compile by yourself ？

**Comment by tkreknin** [comment] 2020-10-17 09:58
> libmediasoupclient_ so.so How to compile by yourself ？

It's better to ask here https://github.com/versatica/libmediasoupclient/ as `mediasoup-client-android` depends on it.
But, afair, once you have all dependencies and tools downloaded (cmake, webrtc) you can build `mediasoup-client-android` using gradle and it will automatically build `libmediasoupclient_ so.so`

**Comment by acoderleex** [comment] 2020-12-30 11:48
waiting for new release to this problem

**Comment by acoderleex** [comment] 2020-12-30 11:50
> I think I have fixed this problem.
> In the webrtc issues, there also have this problem. https://bugs.chromium.org/p/webrtc/issues/detail?id=7587
> The reason is that only one audio device module supported on Android.
> In this code, when join the room, the peerConnectionFactory has been created 4 times and each time will create one audio device module.So I try to create only one peerConnectionFactory in java, and add peerconnection options params in device.cpp.
> Finally, it works.
> I hope it helps you.

Could you release a branch for us?

**Comment by whatisor** [comment] 2021-03-06 16:47
If we talk about pure Java technically, does someone know why a function is possible to become unknown by some bad logic?
It should be constrained from .so binary.

**Comment by whatisor** [comment] 2021-03-07 14:27
Base on update from haiyangwu, this is my solution:
+ Firstly, Close() **both** send transport and receive transport
+ Secondly, dispose() them.
It looks like Webrtc has thread async issue. If dispose before closing all, it becomes the issue.

**Closed** 2021-03-07 14:27 UTC

**Comment by virogu** [comment] 2021-03-25 10:33
> Base on update from haiyangwu, this is my solution:
> 
> * Firstly, Close() **both** send transport and receive transport
> * Secondly, dispose() them.
>   It looks like Webrtc has thread async issue. If dispose before closing all, it becomes the issue.

I seem to have solved the problem through this method you mentioned. I used to leave the meeting frequently and crashed a few times, but now I leave the meeting dozens of times and it won’t crash anymore.

**Comment by ms03001620** [comment] 2022-11-09 03:36
@haiyangwu 
你好，这个crash问题在dev-3.4.0分支上的版本仍然可以出现
我的操作步骤
1.同步最新的client dev3.4.0代码
2.本地编译并发布到local maven
3.demo项目从依赖3.0.8改到3.4.0
4.demo需要升级两处修正代码
 a. mMediasoupDevice.load(routerRtpCapabilities, null); 这个参数变更了根据client测试用例传入一个null对象
 b.SendTransport.produce 创建Producer mMicProducer 和Producer mCamProducer 也加入一个null对象
 c.mMediasoupDevice.createSendTransport,需要传入sctpParameters，传入了client 测试用例中mock的sctpParameters
 d.SendTransport.Listener 追加了新的方法。空实现
5.升级demo项目可以正常启动并连接默认测试服务器。显示lib版本为3.4.0
以上修正也尽可能有问题，请指正

测试
用新版本的demo项目启动设备做为A用户
用新版本的demo项目启动另一设备作为B用户

A用户通过进入setting然后返回来重新进入room（反复操作）
一定概率触发（1/5）No implementation found for void org.webrtc.voiceengine.WebRtcAudioTrack.nativeGetPlayoutDat

这个问题我看了些代码一些不严谨的分析希望能带来帮助
nativeGetPlayoutDat 在写入数据或者处理数据需要Mic的正常工作作为前提。
销毁房间时会断开app和Mic的链接。但是处理数据nativeGetPlayoutDat仍然会被调用

android的摄像头和mic资源可能会失去焦点。导致app的请求资源失效。比如在视频中用户打开了相机或启动了其他的视频app这样原来app申请的摄像资源会被系统回收。也可以在后者使用完毕后重新归还。例如 声音播放焦点
感觉lib中对视频和其他硬件资源的请求应该留给app开发者来做。lib中可以仅资源的数据进行压缩和优化即可

**Comment by RobertWang7752** [comment] 2025-06-18 07:53
> Base on update from haiyangwu, this is my solution:
> 
> * Firstly, Close() **both** send transport and receive transport
> * Secondly, dispose() them.
>   It looks like Webrtc has thread async issue. If dispose before closing all, it becomes the issue.

that's the point, try this:

```
@WorkerThread
private void disposeTransportDevice() {
  Logger.d(TAG, "disposeTransportDevice()");

  // Close mediasoup Transports.
  if (mSendTransport != null) {
      mSendTransport.close();
  }
  if (mRecvTransport != null) {
      mRecvTransport.close();
  }

  try {
    Thread.sleep(200);
  } catch (InterruptedException e) {
    throw new RuntimeException(e);
  }

  if (mSendTransport != null) {
    mSendTransport.dispose();
    mSendTransport = null;
  }
  if (mRecvTransport != null) {
    mRecvTransport.dispose();
    mRecvTransport = null;
  }

  // dispose device.
  if (mMediasoupDevice != null) {
    mMediasoupDevice.dispose();
    mMediasoupDevice = null;
  }

}
```
